[[constraint]]
  name = "github.com/Microsoft/go-winio"
  version = "v0.4.5"

[[constraint]]
  name = "github.com/docker/docker"
  branch = "master"

[[constraint]]
  name = "github.com/docker/go-units"
  version = "v0.3.2"

[[constraint]]
  name = "github.com/google/go-cmp"
  branch = "master"

[[constraint]]
  name = "github.com/gorilla/mux"
  version = "v1.5.0"

[[constraint]]
  name = "golang.org/x/net"
  branch = "master"

[[override]]
  name = "github.com/Nvveen/Gotty"
  source = "https://github.com/ijc25/Gotty.git"
  revision = "a8b993ba6abdb0e0c12b0125c603323a71c7790c"

[[constraint]]
  name = "github.com/xanzy/ssh-agent"
  revision = "ba9c9e33906f58169366275e3450db66139a31a9"
